### ISSUE TITLE
Uncaught TypeError: _this.notificationEl.querySelector is not a function

### ISSUE THREAD

**Issue by sanfo3855** [fmontesi/atom-jolie#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [atom-jolie](https://github.com/fmontesi/atom-jolie) package 0.2.0

### Stack Trace

Uncaught TypeError: _this.notificationEl.querySelector is not a function

```
At /home/matteo/.atom/packages/atom-jolie/node_modules/atom-package-deps/lib/view.js:22

TypeError: _this.notificationEl.querySelector is not a function
    at /packages/atom-jolie/node_modules/atom-package-deps/lib/view.js:22:58
```

### Commands

```
```

### Non-Core Packages

```
atom-jolie 0.2.0 
busy-signal 1.4.3 
intentions 1.1.2 
language-jolie 0.5.0 
linter 2.2.0 
linter-jolie 0.7.1 
linter-ui-default 1.6.2 
```

**Comment by fmontesi** [comment]
Thanks for reporting. I've finally found the issue and now it works fine in my test machine. Let me know if it  still doesn't work for you. Meanwhile, I'll close this as solved.

**Comment by sanfo3855** [comment]
Yes, Problem Solved.
